### ISSUE TITLE
Doesn't open

### ISSUE THREAD

**Issue by Boysiee** [Kuucheen/KC-Cleaner#1]
when i try run it it closes instantly and says this(i do have sty):  
Traceback (most recent call last):
  File "C:\Users\Connor\Downloads\KC-Cleaner-main\KC-Cleaner.py", line 6, in <module>
    from sty import fg
ModuleNotFoundError: No module named 'sty'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "C:\Users\Connor\Downloads\KC-Cleaner-main\KC-Cleaner.py", line 9, in <module>
    from sty import fg
ModuleNotFoundError: No module named 'sty'

**Comment by Boysiee** [comment]
Requirement already satisfied: sty in c:\users\connor\appdata\local\packages\pythonsoftwarefoundation.python.3.10_qbz5n2kfra8p0\localcache\local-packages\python310\site-packages (1.0.4)

**Comment by Kuucheen** [comment]
added a version without sty
